name: Aspect-Based-Sentiment-Analysis
dependencies:
  - python=3.7
  - scikit-learn=0.24.2
  - dataclasses=0.8
  - pip:
      - tensorflow==2.5.0
      - testfixtures==6.17.1
      - transformers==4.8.2
      - optuna==2.8.0
      - spacy==3.1.1
